pipeline:
  docker-build:
    when:
      branch: master
      event: push
    image: plugins/docker
    registry: registry.hub.docker.com
    repo: registry.hub.docker.com/jacobyunker/ghc-2020-demo
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
    tag:
      - latest
      - "b${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:8}"
